namespace prizes
{
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Autofac;
    using Prizes.Api.Mapping;
    using Prizes.Api.Filters;
    using System.Reflection;
    using Microsoft.Extensions.Logging;
    using System.Collections.Generic;
    using prizes.Repository;

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);            
            services.AddOptions();
        }

        public void ConfigureContainer(ContainerBuilder builder)
        {
            AddAutofacRegistrations(builder);
        }

        private void AddAutofacRegistrations(ContainerBuilder builder)
        {
            builder.RegisterAssemblyTypes(
                    Assembly.GetExecutingAssembly())
                .AsImplementedInterfaces();
         //   builder.RegisterType<HttpClient>();
            builder.RegisterType<GlobalExceptionFilter>();

            // #region BLL

            // builder.RegisterAssemblyTypes(
            //      Assembly.GetAssembly(typeof(AuthBll)))
            //      .AsImplementedInterfaces();
            // #endregion

            #region REPOSITORY

            //builder.RegisterType<SurealDataContext>().As<IDataContext>().InstancePerLifetimeScope();
            builder.RegisterAssemblyTypes(
                Assembly.GetAssembly(typeof(ICustomerRepository)))
                .Where(t => t.Name.EndsWith("Repository"))
                .AsImplementedInterfaces();

            // builder.RegisterAssemblyTypes(
            //         Assembly.GetAssembly(typeof(SurealUserManager)))
            //     .Where(t => t.Name.EndsWith("Manager") || t.Name.EndsWith("Validator")

            //     );



            #endregion

            #region COMMON


            // builder.Register(ctx =>
            // {
            //     var options = ctx.Resolve<IOptions<SurealSettings>>();
            //     return options.Value;
            // }).InstancePerLifetimeScope();
            // builder.RegisterAssemblyTypes(Assembly.GetAssembly(typeof(IJsonConverter))).AsImplementedInterfaces().InstancePerLifetimeScope();
            builder.Register(ctx =>
            {
                var logger = ctx.Resolve<ILogger<MappingEngine>>();

                IEnumerable<Assembly> assemblies = new[]
                {
                    //Assembly.GetAssembly(typeof(ICustomerRepository)),
                    Assembly.GetExecutingAssembly()
                };
                //This is how we tell mapping engine to be generated. The list of assemblies cannot be autogenerated
                return new MappingEngine(assemblies, logger);
            }).As<IMappingEngine>().InstancePerLifetimeScope();

            #endregion

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseMvc();
            loggerFactory.AddLog4Net();
        }
    }
}
